name: CI

on:
  pull_request:
    branches: [ main, dev ]
  push:
    branches: [ main, dev ]

jobs:
  frontend-quality:
    uses: santiago-garrote/workflows/.github/workflows/frontend-code-quality.yaml@v1
    with:
      working_directory: frontend
      typecheck_command: pnpm tsc --noEmit
      lint_command: pnpm lint
      format_command: pnpm prettier --check .
      test_command: pnpm vitest run --coverage
      coverage_path: coverage
